image: node:8.11.3

cache:
  paths:
   - node_modules/

before_script:
  - npm install --quiet

test:
  stage: test
  only:
   - dev@eso-community/discord-node-js
  script:
   - npm start

deploy:
  stage: deploy
  only:
   - dev@eso-community/discord-node-js
  script:
   - git remote add heroku https://git.heroku.com/esoc-bot.git
   - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/esoc-bot.git HEAD:master -f
