image: node:8.11.3

cache:
  paths:
   - node_modules/

before_script:
  - npm install --quiet

test:
  stage: test
  script:
   - npm start

deploy:
  stage: deploy
  script:
   - git remote add heroku https://git.heroku.com/esoc-bot.git
   - git push heroku HEAD:master
